### ISSUE TITLE
Need to detach/attach floating IP address from/to instance

### ISSUE THREAD

**Issue by major** [osbuild/exd-deployment#2]
As we deploy a new release of osbuild-composer, we need to detach the floating IP address from the old instance and attach it to the new one. Ansible has the [os_floating_ip](https://docs.ansible.com/ansible/latest/modules/os_floating_ip_module.html) module that can help with this.

By moving the floating IP, users of the system can keep using the same DNS record to access the instance when we make a new deployment.

```yaml
    floating_ip:
      address: 10.0.111.64
      id: 59a56a29-14d8-424d-94ec-fef69c8287d7
```
